-- ==============================================================================
-- CAMS - Campus Asset Management System
-- Module 1: Authentication & Role Management Schema & Seed Data
-- Database: Oracle Database (19c/21c/23c/XE)
-- ==============================================================================

-- 1. Create USERS table
-- Note: Usernames are stored in lowercase to guarantee collation-independent case-insensitivity.
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE USERS (
      USER_ID     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAME        VARCHAR2(100) NOT NULL,
      ROLE        VARCHAR2(30)  NOT NULL CHECK (ROLE IN (''Administrator'', ''Faculty'', ''Technical Staff'')),
      DEPARTMENT  VARCHAR2(100) NOT NULL,
      USERNAME    VARCHAR2(50)  NOT NULL,
      PASSWORD    VARCHAR2(255) NOT NULL,
      CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
      RAISE;
    END IF;
END;
/

-- 2. Optional: Explicit functional index for case-insensitive username index lookup
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_USERS_LOWER_USERNAME ON USERS (LOWER(USERNAME))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      NULL; -- Index may already exist
    END IF;
END;
/

-- 3. Pre-seeded test accounts
-- Notice: Passwords are PBKDF2WithHmacSHA256 hashed (65536 iterations, 16-byte salt).
-- The Java application self-initializes these on startup if missing.
-- Reference plain-text passwords:
--   admin      -> Admin@123      (Role: Administrator)
--   faculty1   -> Faculty@123    (Role: Faculty)
--   tech1      -> Tech@123       (Role: Technical Staff)

COMMIT;
