package com.cams.dao;

import com.cams.model.User;
import com.cams.util.DBConnection;
import com.cams.util.PasswordUtil;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * JDBC Implementation of UserDAO against Oracle Database.
 * Guarantees case-insensitivity by strictly lowercasing usernames prior to query and persistence.
 */
public class UserDAOImpl implements UserDAO {

    private static final Logger LOGGER = Logger.getLogger(UserDAOImpl.class.getName());

    @Override
    public Optional<User> findByUsername(String username) throws SQLException {
        if (username == null || username.trim().isEmpty()) {
            return Optional.empty();
        }

        // Explicitly lowercase before lookup per SRS requirement
        String normalizedUsername = username.trim().toLowerCase();

        String sql = "SELECT USER_ID, NAME, ROLE, DEPARTMENT, USERNAME, PASSWORD, CREATED_AT " +
                     "FROM USERS WHERE USERNAME = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, normalizedUsername);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapRowToUser(rs));
                }
            }
        }
        return Optional.empty();
    }

    @Override
    public Optional<User> findById(Long userId) throws SQLException {
        if (userId == null) {
            return Optional.empty();
        }

        String sql = "SELECT USER_ID, NAME, ROLE, DEPARTMENT, USERNAME, PASSWORD, CREATED_AT " +
                     "FROM USERS WHERE USER_ID = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setLong(1, userId);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapRowToUser(rs));
                }
            }
        }
        return Optional.empty();
    }

    @Override
    public boolean createUser(User user) throws SQLException {
        if (user == null || user.getUsername() == null || user.getPassword() == null) {
            throw new IllegalArgumentException("User and credentials must not be null");
        }

        // Explicitly lowercase username before storage
        String normalizedUsername = user.getUsername().trim().toLowerCase();
        user.setUsername(normalizedUsername);

        String sql = "INSERT INTO USERS (NAME, ROLE, DEPARTMENT, USERNAME, PASSWORD) " +
                     "VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql, new String[]{"USER_ID"})) {

            ps.setString(1, user.getName());
            ps.setString(2, user.getRole());
            ps.setString(3, user.getDepartment());
            ps.setString(4, normalizedUsername);
            ps.setString(5, user.getPassword());

            int affected = ps.executeUpdate();
            if (affected > 0) {
                try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        user.setUserId(generatedKeys.getLong(1));
                    }
                }
                return true;
            }
        }
        return false;
    }

    @Override
    public long countUsers() throws SQLException {
        String sql = "SELECT COUNT(*) FROM USERS";
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        }
        return 0L;
    }

    @Override
    public boolean initSchemaAndSeedIfEmpty() throws SQLException {
        try (Connection conn = DBConnection.getConnection()) {
            boolean tableExists = false;
            // Check if USERS table already exists
            try (Statement checkStmt = conn.createStatement();
                 ResultSet rs = checkStmt.executeQuery("SELECT 1 FROM USERS WHERE 1=0")) {
                tableExists = true;
            } catch (SQLException e) {
                // Table doesn't exist yet, create it
                tableExists = false;
            }

            if (!tableExists) {
                LOGGER.info("USERS table does not exist. Creating USERS table in Oracle...");
                String createTableSql = "CREATE TABLE USERS (" +
                        "USER_ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "NAME VARCHAR2(100) NOT NULL, " +
                        "ROLE VARCHAR2(30) NOT NULL CHECK (ROLE IN ('Administrator', 'Faculty', 'Technical Staff')), " +
                        "DEPARTMENT VARCHAR2(100) NOT NULL, " +
                        "USERNAME VARCHAR2(50) NOT NULL UNIQUE, " +
                        "PASSWORD VARCHAR2(255) NOT NULL, " +
                        "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                        ")";

                try (Statement createStmt = conn.createStatement()) {
                    createStmt.execute(createTableSql);
                    LOGGER.info("USERS table created successfully.");
                } catch (SQLException createEx) {
                    // ORA-00955: name is already used by an existing object
                    if (!createEx.getMessage().contains("ORA-00955")) {
                        throw createEx;
                    }
                }
            }

            // Check if seed data exists
            long count = 0L;
            try (Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM USERS")) {
                if (rs.next()) {
                    count = rs.getLong(1);
                }
            }

            if (count == 0L) {
                LOGGER.info("USERS table is empty. Seeding initial test accounts (Admin, Faculty, Technical Staff)...");

                User admin = new User(null, "System Administrator", "Administrator", "IT Infrastructure",
                        "admin", PasswordUtil.hashPassword("Admin@123"), null);
                User faculty = new User(null, "Dr. Sarah Jenkins", "Faculty", "Computer Science",
                        "faculty1", PasswordUtil.hashPassword("Faculty@123"), null);
                User tech = new User(null, "Alex Rivera", "Technical Staff", "Hardware & Maintenance",
                        "tech1", PasswordUtil.hashPassword("Tech@123"), null);

                createUser(admin);
                createUser(faculty);
                createUser(tech);

                LOGGER.info("Seeding completed successfully. Seeded accounts: admin, faculty1, tech1");
            } else {
                LOGGER.info("USERS table already populated with " + count + " users.");
            }

            return true;
        }
    }

    private User mapRowToUser(ResultSet rs) throws SQLException {
        User user = new User();
        user.setUserId(rs.getLong("USER_ID"));
        user.setName(rs.getString("NAME"));
        user.setRole(rs.getString("ROLE"));
        user.setDepartment(rs.getString("DEPARTMENT"));
        user.setUsername(rs.getString("USERNAME"));
        user.setPassword(rs.getString("PASSWORD"));
        user.setCreatedAt(rs.getTimestamp("CREATED_AT"));
        return user;
    }
}
