-- ==============================================================================
-- CAMS - Campus Asset Management System
-- Module 2: Asset Management Schema & Seed Data
-- Database: Oracle Database (xepdb1)
-- ==============================================================================

-- 1. Drop existing ASSETS table for development environment idempotency
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ASSETS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
            RAISE;
        END IF;
END;
/

-- 2. Create ASSETS table with single STATUS column and retirement audit fields
CREATE TABLE ASSETS (
    ASSET_ID         VARCHAR2(50) PRIMARY KEY,
    ASSET_NAME       VARCHAR2(100) NOT NULL,
    CATEGORY         VARCHAR2(50) NOT NULL,
    DEPARTMENT       VARCHAR2(50) NOT NULL,
    PURCHASE_DATE    DATE NOT NULL,
    PURCHASE_COST    NUMBER(12, 2) NOT NULL CHECK (PURCHASE_COST > 0),
    VENDOR_ID        VARCHAR2(50),
    WARRANTY_EXPIRY  DATE,
    STATUS           VARCHAR2(30) DEFAULT 'AVAILABLE' NOT NULL 
                     CHECK (STATUS IN ('AVAILABLE', 'ISSUED', 'UNDER_MAINTENANCE', 'DISPOSED')),
    LOCATION         VARCHAR2(100) NOT NULL,
    DISPOSED_DATE    DATE,
    DISPOSAL_REASON  VARCHAR2(255),
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_ASSET_WARRANTY CHECK (WARRANTY_EXPIRY IS NULL OR WARRANTY_EXPIRY >= PURCHASE_DATE)
);

-- 3. Helpful functional indexes for filter & search performance
CREATE INDEX IDX_ASSETS_DEPT ON ASSETS (DEPARTMENT);
CREATE INDEX IDX_ASSETS_CAT ON ASSETS (CATEGORY);
CREATE INDEX IDX_ASSETS_STATUS ON ASSETS (STATUS);
CREATE INDEX IDX_ASSETS_LOWER_NAME ON ASSETS (LOWER(ASSET_NAME));

-- 4. Initial Seed Data (12 sample assets across departments, categories & statuses)
INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-CSE-001', 'Dell Precision 5820 Workstation', 'Computer', 'CSE', DATE '2025-01-15', 85000.00, 'VND-DELL-01', DATE '2028-01-15', 'AVAILABLE', 'CSE Lab 1');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-CSE-002', 'Cisco Catalyst 24-Port Gigabit Switch', 'Computer', 'CSE', DATE '2024-06-10', 45000.00, 'VND-CISCO-02', DATE '2027-06-10', 'AVAILABLE', 'CSE Lab 1');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-CSE-003', 'Apple iMac 24-inch M3', 'Computer', 'CSE', DATE '2025-02-20', 145000.00, 'VND-APPLE-04', DATE '2027-02-20', 'AVAILABLE', 'CSE Lab 1');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-IT-001', 'Epson EB-2250U 3LCD Projector', 'Classroom Asset', 'IT', DATE '2024-09-05', 68000.00, 'VND-EPSON-03', DATE '2027-09-05', 'AVAILABLE', 'Room 101');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-IT-002', 'Lenovo ThinkCentre Neo 50t', 'Computer', 'IT', DATE '2024-11-14', 52000.00, 'VND-LENOVO-01', DATE '2027-11-14', 'AVAILABLE', 'IT Lab 1');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-ECE-001', 'Tektronix 100MHz Digital Storage Oscilloscope', 'Laboratory Equipment', 'ECE', DATE '2024-03-20', 78000.00, 'VND-TEK-05', DATE '2027-03-20', 'AVAILABLE', 'ECE Lab 1');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-ECE-002', 'Rigol Function / Arbitrary Waveform Generator', 'Laboratory Equipment', 'ECE', DATE '2024-04-12', 34000.00, 'VND-RIGOL-02', DATE '2026-04-12', 'AVAILABLE', 'ECE Lab 1');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-EEE-001', 'Chroma Programmable AC Power Source', 'Laboratory Equipment', 'EEE', DATE '2023-08-18', 195000.00, 'VND-CHROMA-08', DATE '2026-08-18', 'AVAILABLE', 'Room 101');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-MECH-001', 'Universal Hydraulic Tensile Testing Machine', 'Laboratory Equipment', 'MECH', DATE '2023-10-02', 320000.00, 'VND-TEST-11', DATE '2026-10-02', 'UNDER_MAINTENANCE', 'Room 101');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-CIVIL-001', 'Leica Geosystems Digital Theodolite', 'Laboratory Equipment', 'CIVIL', DATE '2023-05-15', 89000.00, 'VND-LEICA-04', DATE '2026-05-15', 'AVAILABLE', 'Room 101');

INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION)
VALUES ('AST-FUR-001', 'Ergonomic High-Back Lab Chairs (Set of 10)', 'Furniture', 'CSE', DATE '2024-01-10', 42000.00, 'VND-GODREJ-06', DATE '2026-01-10', 'AVAILABLE', 'CSE Lab 1');

-- Pre-retired / disposed asset for testing soft-delete and lifecycle viewing
INSERT INTO ASSETS (ASSET_ID, ASSET_NAME, CATEGORY, DEPARTMENT, PURCHASE_DATE, PURCHASE_COST, VENDOR_ID, WARRANTY_EXPIRY, STATUS, LOCATION, DISPOSED_DATE, DISPOSAL_REASON)
VALUES ('AST-RET-001', 'Legacy Dell OptiPlex 780 Desktop', 'Computer', 'CSE', DATE '2018-07-22', 32000.00, 'VND-DELL-01', DATE '2021-07-22', 'DISPOSED', 'Room 101', DATE '2025-01-10', 'Hardware obsolete and unserviceable motherboards');

COMMIT;
