-- ==============================================================================
-- CAMS - Campus Asset Management System
-- Module 2B: Category-Specific Asset Details Schema
-- Database: Oracle Database (xepdb1)
-- ==============================================================================

-- 1. Computer Details (Category: Computer)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMPUTER_DETAILS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE COMPUTER_DETAILS (
    ASSET_ID     VARCHAR2(50) PRIMARY KEY,
    CPU          VARCHAR2(100),
    MONITOR      VARCHAR2(100),
    KEYBOARD     VARCHAR2(100),
    MOUSE        VARCHAR2(100),
    PRINTER      VARCHAR2(100),
    SOFTWARE     VARCHAR2(255),
    IP_ADDRESS   VARCHAR2(50),
    CONSTRAINT FK_COMP_ASSET FOREIGN KEY (ASSET_ID) 
        REFERENCES ASSETS(ASSET_ID) ON DELETE CASCADE
);

-- 2. Classroom Details (Category: Classroom Asset)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLASSROOM_DETAILS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE CLASSROOM_DETAILS (
    ASSET_ID          VARCHAR2(50) PRIMARY KEY,
    FURNITURE_DESC    VARCHAR2(255),
    PROJECTOR         VARCHAR2(100),
    SMART_BOARD       VARCHAR2(100),
    AC                VARCHAR2(100),
    SEATING_CAPACITY  NUMBER(6) CHECK (SEATING_CAPACITY IS NULL OR SEATING_CAPACITY > 0),
    CONSTRAINT FK_CLASS_ASSET FOREIGN KEY (ASSET_ID) 
        REFERENCES ASSETS(ASSET_ID) ON DELETE CASCADE
);

-- 3. Laboratory Equipment Details (Category: Laboratory Equipment)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LAB_DETAILS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE LAB_DETAILS (
    ASSET_ID               VARCHAR2(50) PRIMARY KEY,
    EQUIPMENT_TYPE         VARCHAR2(100),
    EQUIPMENT_CONDITION    VARCHAR2(100),
    LAST_CALIBRATION_DATE  DATE,
    CONSTRAINT FK_LAB_ASSET FOREIGN KEY (ASSET_ID) 
        REFERENCES ASSETS(ASSET_ID) ON DELETE CASCADE
);

-- 4. Furniture Details (Category: Furniture)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FURNITURE_DETAILS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE FURNITURE_DETAILS (
    ASSET_ID         VARCHAR2(50) PRIMARY KEY,
    FURNITURE_TYPE   VARCHAR2(100),
    MATERIAL         VARCHAR2(100),
    QUANTITY         NUMBER(6) CHECK (QUANTITY IS NULL OR QUANTITY > 0),
    CONSTRAINT FK_FURN_ASSET FOREIGN KEY (ASSET_ID) 
        REFERENCES ASSETS(ASSET_ID) ON DELETE CASCADE
);

COMMIT;
EXIT;
